### PR TITLE
Add some security headers

### PR DESCRIPTION
**Pull request by eddydu44**
Today security is very important and I think everyone should use these basic headers.
I follow the recommendations of [DareBoost](**https://www.dareboost.com/**).

### CODE REVIEW

**Comment by maximejobin** [comment]
I don't think the template should be modified to add these headers. I think they should be added in the `rocket-nginx.ini` file if they make sense. By "if they make sense", I mean if they *must* and *can* be applied to all websites in a generic way that won't alter the website's behaviour in a negative way.  We want to avoid creating problems in any way.  If it could cause problems, I suggest these headers to be added as options.

Please let me know what you think.

**Comment by eddydu44** [comment]
Maybe we can open a new branch "more secure" ^^
otherwise it's possible to add a condition at the beginning, and if some people face to problem they pass the variable to 0 (like the debug)

**Comment by eddydu44** [comment]
#https://github.com/eddydu44/rocket-nginx/commit/84a4f87c1cd732c4bf9e6db0293fda09e70c3d4a

**Comment by eddydu44** [comment]
I'm sorry I don't know how to add a commit to an existing pull request ?

**Comment by maximejobin** [comment]
The right way to do this is to edit the `rocket-nginx.ini`. You can make it fit your reality. At this point, I don't have enough information to push that in the main branch and impact everyone with it.

**Pull request closed without merging**
