### PR TITLE
Detect https prefix with X-Forwarded-Proto header

### PR DESCRIPTION
**Pull request by daohoangson**

### CODE REVIEW

**Comment by maximejobin** [comment]
This pull request cannot be accepted as-is because it is incomplete. That said, thank you for your work and it will be used as a start for the full implementation.

About this pull request, see this for reference:

Documentation:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

Nginx support:
https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

Other:
https://stackoverflow.com/questions/13111080/what-is-a-full-specification-of-x-forwarded-proto-http-header

**Comment by maximejobin** [comment]
These headers should be considered:

Official:

    Forwarded: by=<identifier>;for=<identifier>;host=<host>;proto=https

Non official:

    X-Forwarded-Proto: https
    Front-End-Https: on     # Microsoft
    X-Forwarded-Protocol: https 
    X-Forwarded-Ssl: on 
    X-Url-Scheme: https

**Comment by mathieu-aubin** [comment]
must make sure that ipv6 are contained between " " as such

    Forwarded: for="[2001:41FF:FFF:FFF::3233]";proto=https

what i worked on and am using to this day on v4.4ce.ca / v6.4ce.ca (ip return service) is this
```
    # Map visitor info to a variable for use where needed (aka forwarded headers)
    map $remote_addr    $real_ip_variable {
        default                    "$remote_addr";        # RFC 7239 - Unix socket names cant be represented
        ~^[0-9.]+$               "$remote_addr";        # IPv4 addresses can be left alone
        ~^[0-9A-Fa-f:.]+$    "\"[$remote_addr]\""; # IPv6 addresses need to be bracketed and quoted "[]"
    }

    # this somewhat seems to make no sense as the default could very well be $real_ip_variable .. but..
    map $remote_addr $proxy_forwarded_elem {
        default                    "for=unknown";
        ~^[0-9.]+$               "for=$real_ip_variable";
        ~^[0-9A-Fa-f:.]+$    "for=$real_ip_variable";
    }
```
you can then use $real_ip_variable as ip within your header calls

scuse moi pour le formatting du code - j'ai ben essayé mais la, j'ai d'autre choses sur le feu! Au plaisir vieux

**Comment by maximejobin** [comment]
I'm just unsure why all this should matter to Rocket-Nginx.

The goal is _**just**_ to server the HTTP or HTTPS file generated by WP-Rocket. Why should Rocket-Nginx care about the IP ?

Maybe I misunderstand something here...

**Pull request closed without merging**
